apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: revect
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "100"
        autoscaling.knative.dev/initialScale: "0"

    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - name: revect
          image: docker.io/zachrebuild/revect.io:5
          ports:
            - name: http1
              containerPort: 3000
          env:
            - name: AI_EMBEDDING_MODEL
              value: "text-embedding-3-small"
            - name: AI_EMBEDDING_SIZE
              value: "1024"
            - name: AI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: openaikey
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: apisecret
          resources:
            limits:
              memory: 1Gi
              cpu: 2000m
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 3000
